COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_SRCDIRS := src
CXXFLAGS += -DESPRESSIO_SERIALIZABLE
CXXFLAGS += -DESPRESSIO_SERIALIZABLE_VERSION_MAJOR=0
CXXFLAGS += -DESPRESSIO_SERIALIZABLE_VERSION_MINOR=0
CXXFLAGS += -DESPRESSIO_SERIALIZABLE_VERSION_PATCH=1
CXXFLAGS += -DESPRESSIO_SERIALIZABLE_VERSION_STRING=\"0.0.1\"