name=Flowduino ESPressio-Serializable
version=0.0.1
author=Simon J. Stuart
maintainer=Flowduino.com
sentence=Serializable Library intended for use with all microcontrollers
paragraph=This library is intended to be used with the all microcontrollers. It is designed to allow the user to very easily Serialize and Deserialize objects to and from JSON, and of course exchange them via either WebSockets or REST APIs.
category=Communication
url=https://github.com/Flowduino/ESPressio-Serializable
architectures=*
dependencies=ArduinoJson