cmake_minimum_required(VERSION 3.16)
project(ESPressioSerializableTests LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_executable(espressio_serializable_tests test_serializable.cpp)
target_include_directories(espressio_serializable_tests PRIVATE ../src)
add_executable(espressio_serializable_v06_tests test_v06.cpp)
target_include_directories(espressio_serializable_v06_tests PRIVATE ../src)
enable_testing()
add_test(NAME ESPressioSerializableTests COMMAND espressio_serializable_tests)
add_test(NAME ESPressioSerializableV06Tests COMMAND espressio_serializable_v06_tests)
