[platformio]
default_envs = esp32, esp32s3, esp32s3_psram

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ..
build_flags = -std=gnu++17

[env:esp32]
board = esp32dev

[env:esp32s3]
board = esp32-s3-devkitc-1

[env:esp32s3_psram]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
build_flags =
    ${env.build_flags}
    -DBOARD_HAS_PSRAM
